PgsTwitter/PgsTwitter/Entities/Tag.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Amazon.DynamoDBv2.DataModel;

namespace PgsTwitter.Entities
{
    [DynamoDBTable(Table.Tag)]
    public class Tag
    {
        [DynamoDBHashKey]
        public string Name { get; set; }

        [DynamoDBProperty]
        public int Count { get; set; }
    }
}

PgsTwitter/PgsTwitter/Models/Tag/TagModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PgsTwitter.Models.Tag
{
    public class TagModel
    {
        public string Name { get; set; }
        public int Count { get; set; }

        public List<Entities.Message> Message { get; set; } 
    }
}

PgsTwitter/PgsTwitter/Controllers/TagController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PgsTwitter.Models.Tag;
using PgsTwitter.Services;

namespace PgsTwitter.Controllers
{
    public class TagController : BaseController
    {
        public ActionResult Index()
        {
            var service = new MessageService(Context);
            var tags = service.GetAllTags();
            var model = tags.Select(tag => new TagModel()
                {
                    Count = tag.Count,
                    Name = tag.Name
                });
            return View(model);
        }

        public ActionResult Tag(string id)
        {
            var service = new MessageService(Context);
            var messages = service.GetMessagesByTag(id);
            return View(messages);
        }

    }
}

PgsTwitter/PgsTwitter/Views/Tag/Index.cshtml
@model System.Collections.Generic.IEnumerable<PgsTwitter.Models.Tag.TagModel>

@{
    ViewBag.Title = "Index";
}

<h2>Tags</h2>

    <ul>
        @{
            foreach (var tag in Model)
            {
                <li>
                    @Html.ActionLink(tag.Name, "Tag", new {id = tag.Name}, null) : @tag.Count
                </li>
            }
        }

    </ul>

PgsTwitter/PgsTwitter/Views/Tag/Tag.cshtml
@model System.Collections.Generic.ICollection<PgsTwitter.Entities.Message>

@{
    ViewBag.Title = "Index";
}

<h2>Messages</h2>

<table>
@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Sender)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PostedOn )
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Text )
        </td>
    </tr>
}
</table>